import type { Metadata } from "next";
import { companyName } from '@/constants/index' 
import * as Com from '@/components/index'
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin","greek"] });

export const metadata: Metadata = {
  title: companyName,
  description: "Generated by create next app",
  icons: {
    icon: ['/favion.ico?v=4'],
    apple: ['/favicon-16x16.png'],
    shortcut: ['/apple-touch-icon.png ']
  }
};

export default function RootLayout({
  children,
}: Readonly<{  
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`scroll-smooth`}>
        <Com.Header />
        {children}
        <Com.SuccessSnippets />
        <Com.Form />
        <Com.Accordion />
        <Com.Footer /> 
      </body>
    </html>
  );
}
